import Head from 'next/head';
import { Layout } from '../../../components/Layout/index.jsx';

const Home = () => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <main>
          <div className='pagehome'>
            <div className='pagehome_content'>
              <h1>Home Header</h1>
              <div className='content'>Content</div>
            </div>
          </div>
        </main>
      </Layout>
    </>
  );
};

export default Home;
