import Head from 'next/head';

import { Layout } from '../components/Layout/index.jsx';

export default function Home() {
  return (
    <div>
      <Head>
        <title>@torik135</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <main>
          <div className='pagehome'>
            <div className='pagehome_content'>
              <h1>
                <span id='pagehome_header'>Personal</span> Website
              </h1>
              <div className='content'>
                Content Content Content Content Content Content Content Content
                Content Content Content Content Content Content Content Content
                Content Content Content Content Content Content Content Content
                Content Content Content Content Content Content Content Content
                Content Content Content Content Content Content Content Content
                Content Content Content Content Content Content Content Content
                Content Content Content Content Content Content Content Content
                Content Content Content Content Content Content Content Content
                Content Content Content Content Content Content Content Content
                Content Content Content Content Content Content Content Content
                Content Content Content Content Content Content Content Content
                Content Content Content Content Content Content Content Content
                Content Content Content Content Content Content Content Content
                Content Content Content Content Content Content Content Content
                Content Content Content Content Content Content Content Content
                Content Content Content Content Content Content Content Content
                Content Content Content Content Content Content Content Content
                Content Content Content Content Content Content Content Content
                Content Content Content Content Content Content Content Content
                Content Content Content Content Content Content Content Content
                Content Content Content Content Content Content Content Content
                Content Content Content Content Content Content Content Content
                Content Content Content Content Content Content Content Content
                Content Content Content Content Content Content Content Content
                Content Content Content Content Content Content Content Content
                Content Content Content Content Content Content Content Content{' '}
              </div>
            </div>
          </div>
        </main>
      </Layout>
    </div>
  );
}
